#!/bin/sh

#############################################################################
# Version 0.9.0-RELEASE (01-02-2023)
#############################################################################

#############################################################################
# Copyright 2023 Nozel/Sebas Veeke. Licenced under a Creative Commons
# Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# See https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# Contact:
# > e-mail      mail@nozel.org
# > GitHub      nozel-org
#############################################################################

#############################################################################
# VARIABLES
#############################################################################

# serverbot version
BOTMANAGER_VERSION='0.9.0'

# commands
WGET="$(command -v wget)"

# program variables
BOTMANAGER_CONFIG_SOURCE='https://raw.githubusercontent.com/nozel-org/botmanager/main/resources/botmanager.conf'
BOTMANAGER_LOG='/var/log/botmanager.log'

# colors
NC='\033[0;0m'
BOLD='\033[1m'
#UNDER='\033[4m'
#WHITE='\033[1;37m'
#RED='\033[0;31m'
#GREEN='\033[0;32m'
#YELLOW='\033[1;33m'
LRED='\033[1;31m'
#LGREEN='\033[1;32m'
#LMAGENTA='\033[1;35m'
#LCYAN='\033[1;36m'

####################################################################################################
# ARGUMENT HANDLING
####################################################################################################

# populate validation variables with zeros for validation
ARGUMENT_VERSION='0'
ARGUMENT_HELP='0'
ARGUMENT_CRON='0'
ARGUMENT_DISABLE_CRON='0'
ARGUMENT_OVERVIEW='0'
ARGUMENT_INSTALL='0'
ARGUMENT_REMOVE='0'
ARGUMENT_UPDATE='0'
ARGUMENT_UNATTENDED='0'

# read arguments
while test -n "$1"; do
    case "$1" in
        # options
        --version|-version|version|--v|-v)
            ARGUMENT_VERSION='1'
            shift
            ;;

        --help|-help|help|--h|-h)
            ARGUMENT_HELP='1'
            shift
            ;;
        
        --cron|-cron|cron)
            ARGUMENT_CRON='1'
            shift
            ;;

        --disable-cron|-disable-cron|disable-cron)
            ARGUMENT_DISABLE_CRON='1'
            shift
            ;;

        # features
        --overview|overview|-o|--list|list|-l|--show|show)
            ARGUMENT_OVERVIEW='1'
            shift
            ;;

        --install|install|-i)
            ARGUMENT_INSTALL='1'
            shift
            ;;

        --remove|remove|-r)
            ARGUMENT_REMOVE='1'
            shift
            ;;

        --update|update|-u)
            ARGUMENT_UPDATE='1'
            shift
            ;;

        --unattended)
            ARGUMENT_UNATTENDED='1'
            shift
            ;;

        # other
        *)
            ARGUMENT_NONE='1'
            shift
            ;;
    esac
done


####################################################################################################
# REQUIREMENT AND VALIDATION FUNCTIONS
####################################################################################################

requirement_root() {
    # show error when botmanager isn't run with root privileges
    if [ "$(id -u)" -ne '0' ]; then
        error 'botmanager: error: used argument must be run with root privileges'
    fi
}

requirement_os() {
    # show error when freebsd-version cannot be found
    if [ ! "$(command -v freebsd-version)" ]; then
        error 'botmanager: operating system is not supported'
    fi
}

requirement_wget() {
    # show error when wget cannot be found
    if [ ! "$(command -v wget)" ]; then
        error 'botmanager: error: wget is not installed'
    fi
}

####################################################################################################
# GENERAL FUNCTIONS
####################################################################################################

option_version() {
    printf "%bbotmanager %s %b\n" "${BOLD}" "${BOTMANAGER_VERSION}" "${NC}"
    printf "%bCopyright (C) 2023 Nozel.%b\n" "${BOLD}" "${NC}"
    printf "%bLicense CC Attribution-NonCommercial-ShareAlike 4.0 Int.%b\n\n" "${BOLD}" "${NC}"
    printf "%bWritten by Sebas Veeke%b\n" "${BOLD}" "${NC}"
}

option_help() {
    printf "%bUsage:%b\n" "${BOLD}" "${NC}"
    printf "%b  botmanager [feature]...%b\n" "${BOLD}" "${NC}"
    printf "%b  botmanager [option]...%b\n\n" "${BOLD}" "${NC}"
    printf "%bFeatures:%b\n" "${BOLD}" "${NC}"
    printf "  -o, --overview             Shows the bot status on this device\n"
    printf "  -i, --install              Install one of the bots\n"
    printf "  -r, --remove               Remove a installed bot\n"
    printf "  -u, --update               Update all installed bots\n"
    printf "      --unattended           Add to --update for unattended action\n"
    printf "%bOptions:%b\n" "${BOLD}" "${NC}"
    printf "  --cron                     Set daily automatic update\n"
    printf "  --disable-cron             Set daily automatic update\n"
    printf "  --help                     Display this help and exit\n"
    printf "  --version                  Display version information and exit\n"
}

option_cron() {
    requirement_root

    printf "%b[1/2] Adding cronjob for automatic bot updates%b\n" "${BOLD}" "${NC}"
    rm -f /etc/cron.d/botmanager
    printf "# This cronjob manages daily automated botmanager program updates\n" > /etc/cron.d/botmanager
    printf "0 1 * * * root /usr/local/bin/botmanager --update --unattended\n" >> /etc/cron.d/botmanager
    printf "%b[2/2] Changing cronjob owner and group to root:wheel%b\n" "${BOLD}" "${NC}"
    chown root:wheel /etc/cron.d/botmanager
    printf "\n%bAll done! \\\( ^ ᴗ ^ )/%b\n" "${BOLD}" "${NC}"
    printf "\n%bYour new schedule can be found in /etc/cron.d/botmanager.%b\n" "${BOLD}" "${NC}"
}

option_disable_cron() {
    requirement_root

    printf "%b[1] Removing botmanager cronjob%b\n" "${BOLD}" "${NC}"
    rm -f /etc/cron.d/botmanager
    printf "\n%bAll done! \\\( ^ ᴗ ^ )/%b\n" "${BOLD}" "${NC}"
}

####################################################################################################
# SUPPORT FUNCTIONS
####################################################################################################

error() {
    printf "%b%s%b\n" "${LRED}" "$@" "${NC}"
    exit 1
}

notice() {
    printf "%b%s%b\n" "${LRED}" "$@" "${NC}"
}

send_error_to_log() {
    DATE="$(date +%Y-%m-%d)"
    TIME="$(date +%H:%M:%S)"
    printf "[%s][%s][ERROR] %s %s %s\n" "${DATE}" "${TIME}" "${1}" "${2}" "${3}" >> ${BOTMANAGER_LOG}
}

send_notice_to_log() {
    DATE="$(date +%Y-%m-%d)"
    TIME="$(date +%H:%M:%S)"
    printf "[%s][%s][NOTICE] %s %s %s\n" "${DATE}" "${TIME}" "${1}" "${2}" "${3}" >> ${BOTMANAGER_LOG}
}

version() { 
    printf "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; 
}

remove_temp_files() {
    if [ -f "${BOTMANAGER_CONFIG_TEMP_FILE}" ]; then
        rm "${BOTMANAGER_CONFIG_TEMP_FILE}"
    fi
}

####################################################################################################
# GATHER FUNCTIONS
####################################################################################################

gather_latest_bot_information() {
    BOTMANAGER_CONFIG_TEMP_FILE="$(mktemp)"
    "${WGET}" -q "${BOTMANAGER_CONFIG_SOURCE}" -O "${BOTMANAGER_CONFIG_TEMP_FILE}"
    if [ -f "${BOTMANAGER_CONFIG_TEMP_FILE}" ]; then
        . "${BOTMANAGER_CONFIG_TEMP_FILE}"
    else
        error "Can't fetch remote bot information, check your internet connection"
    fi
}

gather_local_bot_information() {
    BOTMANAGER_INSTALLED='0'
    SERVERBOT_INSTALLED='0'
    BACKUPBOT_INSTALLED='0'
    UPTIMEBOT_INSTALLED='0'
    UPDATEBOT_INSTALLED='0'
    SPARRY_INSTALLED='0'
    TORBOT_INSTALLED='0'

    if [ -f "${BOTMANAGER_PROGRAM_DESTINATION}" ]; then
        BOTMANAGER_INSTALLED='YES'
        BOTMANAGER_INSTALL_LOCATION="${BOTMANAGER_PROGRAM_DESTINATION}"
        BOTMANAGER_LOCAL_VERSION="${BOTMANAGER_VERSION}"
        if [ "$(version "${BOTMANAGER_LOCAL_VERSION}")" -ge "$(version "${BOTMANAGER_LATEST_VERSION}")" ]; then
            BOTMANAGER_STATUS='OK'
        else
            BOTMANAGER_STATUS="UPDATE"
        fi
    else
        BOTMANAGER_INSTALLED='NO'
        BOTMANAGER_INSTALL_LOCATION=''
        BOTMANAGER_LOCAL_VERSION=''
        BOTMANAGER_LATEST_VERSION=''
    fi
    if [ -f "${SERVERBOT_PROGRAM_DESTINATION}" ]; then
        SERVERBOT_INSTALLED='YES'
        SERVERBOT_INSTALL_LOCATION="${SERVERBOT_PROGRAM_DESTINATION}"
        SERVERBOT_LOCAL_VERSION="$(< "${SERVERBOT_PROGRAM_DESTINATION}" grep "SERVERBOT_VERSION=" | cut -f 2 -d '=' | tr -d \')"
        if [ "$(version "${SERVERBOT_LOCAL_VERSION}")" -ge "$(version "${SERVERBOT_LATEST_VERSION}")" ]; then
            SERVERBOT_STATUS='OK'
        else
            SERVERBOT_STATUS="UPDATE"
        fi
    else
        SERVERBOT_INSTALLED='NO'
        SERVERBOT_LOCAL_VERSION=''
        SERVERBOT_LATEST_VERSION=''
    fi
    if [ -f "${BACKUPBOT_PROGRAM_DESTINATION}" ]; then
        BACKUPBOT_INSTALLED='YES'
        BACKUPBOT_INSTALL_LOCATION="${BACKUPBOT_PROGRAM_DESTINATION}"
        BACKUPBOT_LOCAL_VERSION="$(< "${BACKUPBOT_PROGRAM_DESTINATION}" grep "BACKUPBOT_VERSION=" | cut -f 2 -d '=' | tr -d \')"
        if [ "$(version "${BACKUPBOT_LOCAL_VERSION}")" -ge "$(version "${BACKUPBOT_LATEST_VERSION}")" ]; then
            BACKUPBOT_STATUS='OK'
        else
            BACKUPBOT_STATUS="UPDATE"
        fi
    else
        BACKUPBOT_INSTALLED='NO'
        BACKUPBOT_LOCAL_VERSION=''
        BACKUPBOT_LATEST_VERSION=''
    fi
    if [ -f "${UPTIMEBOT_PROGRAM_DESTINATION}" ]; then
        UPTIMEBOT_INSTALLED='YES'
        UPTIMEBOT_INSTALL_LOCATION="${UPTIMEBOT_PROGRAM_DESTINATION}"
        UPTIMEBOT_LOCAL_VERSION="$(< "${UPTIMEBOT_PROGRAM_DESTINATION}" grep "UPTIMEBOT_VERSION=" | cut -f 2 -d '=' | tr -d \')"
        if [ "$(version "${UPTIMEBOT_LOCAL_VERSION}")" -ge "$(version "${UPTIMEBOT_LATEST_VERSION}")" ]; then
            UPTIMEBOT_STATUS='OK'
        else
            UPTIMEBOT_STATUS="UPDATE"
        fi
    else
        UPTIMEBOT_INSTALLED='NO'
        UPTIMEBOT_LOCAL_VERSION=''
        UPTIMEBOT_LATEST_VERSION=''
    fi
    if [ -f "${UPDATEBOT_PROGRAM_DESTINATION}" ]; then
        UPDATEBOT_INSTALLED='YES'
        UPDATEBOT_INSTALL_LOCATION="${UPDATEBOT_PROGRAM_DESTINATION}"
        UPDATEBOT_LOCAL_VERSION="$(< "${UPDATEBOT_PROGRAM_DESTINATION}" grep "UPDATEBOT_VERSION=" | cut -f 2 -d '=' | tr -d \')"
        if [ "$(version "${UPDATEBOT_LOCAL_VERSION}")" -ge "$(version "${UPDATEBOT_LATEST_VERSION}")" ]; then
            UPDATEBOT_STATUS='OK'
        else
            UPDATEBOT_STATUS="UPDATE"
        fi
    else
        UPDATEBOT_INSTALLED='NO'
        UPDATEBOT_LOCAL_VERSION=''
        UPDATEBOT_LATEST_VERSION=''
    fi
    if [ -f "${SPARRY_PROGRAM_DESTINATION}" ]; then
        SPARRY_INSTALLED='YES'
        SPARRY_INSTALL_LOCATION="${SPARRY_PROGRAM_DESTINATION}"
        SPARRY_LOCAL_VERSION="$(< "${SPARRY_PROGRAM_DESTINATION}" grep "SPARRY_VERSION=" | cut -f 2 -d '=' | tr -d \')"
        if [ "$(version "${SPARRY_LOCAL_VERSION}")" -ge "$(version "${SPARRY_LATEST_VERSION}")" ]; then
            SPARRY_STATUS='OK'
        else
            SPARRY_STATUS="UPDATE"
        fi
    else
        SPARRY_INSTALLED='NO'
        SPARRY_LOCAL_VERSION=''
        SPARRY_LATEST_VERSION=''
    fi
    if [ -f "${TORBOT_PROGRAM_DESTINATION}" ]; then
        TORBOT_INSTALLED='YES'
        TORBOT_INSTALL_LOCATION="${TORBOT_PROGRAM_DESTINATION}"
        TORBOT_LOCAL_VERSION="$(< "${TORBOT_PROGRAM_DESTINATION}" grep "TORBOT_VERSION=" | cut -f 2 -d '=' | tr -d \')"
        if [ "$(version "${TORBOT_LOCAL_VERSION}")" -ge "$(version "${TORBOT_LATEST_VERSION}")" ]; then
            TORBOT_STATUS='OK'
        else
            TORBOT_STATUS="UPDATE"
        fi
    else
        TORBOT_INSTALLED='NO'
        TORBOT_LOCAL_VERSION=''
        TORBOT_LATEST_VERSION=''
    fi
}

####################################################################################################
# FEATURE FUNCTIONS
####################################################################################################

feature_overview() {
    gather_latest_bot_information
    gather_local_bot_information

    DIVIDER="=========================================================================================="
    HEADER="\n %-4s %-12s %-10s %-7s %-6s %-7s %-20s\n"
    FORMAT=" %-4s %-12s %-10s %-7s %-6s %-7s %-20s\n"
    WIDTH="90"
    printf "%b" "${BOLD}"
    printf "${HEADER}" "NR" "BOT" "INSTALLED" "STATUS" "LOCAL" "LATEST" "LOCATION"
    printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"

    printf "${FORMAT}" "1" "${BOTMANAGER_NAME}" "${BOTMANAGER_INSTALLED}" "${BOTMANAGER_STATUS}" "${BOTMANAGER_LOCAL_VERSION}" "${BOTMANAGER_LATEST_VERSION}" "${BOTMANAGER_INSTALL_LOCATION}"
    printf "${FORMAT}" "2" "${SERVERBOT_NAME}" "${SERVERBOT_INSTALLED}" "${SERVERBOT_STATUS}" "${SERVERBOT_LOCAL_VERSION}" "${SERVERBOT_LATEST_VERSION}" "${SERVERBOT_INSTALL_LOCATION}"
    printf "${FORMAT}" "3" "${BACKUPBOT_NAME}" "${BACKUPBOT_INSTALLED}" "${BACKUPBOT_STATUS}" "${BACKUPBOT_LOCAL_VERSION}" "${BACKUPBOT_LATEST_VERSION}" "${BACKUPBOT_INSTALL_LOCATION}"
    printf "${FORMAT}" "4" "${UPTIMEBOT_NAME}" "${UPTIMEBOT_INSTALLED}" "${UPTIMEBOT_STATUS}" "${UPTIMEBOT_LOCAL_VERSION}" "${UPTIMEBOT_LATEST_VERSION}" "${UPTIMEBOT_INSTALL_LOCATION}"
    printf "${FORMAT}" "5" "${UPDATEBOT_NAME}" "${UPDATEBOT_INSTALLED}" "${UPDATEBOT_STATUS}" "${UPDATEBOT_LOCAL_VERSION}" "${UPDATEBOT_LATEST_VERSION}" "${UPDATEBOT_INSTALL_LOCATION}"
    printf "${FORMAT}" "6" "${SPARRY_NAME}" "${SPARRY_INSTALLED}" "${SPARRY_STATUS}" "${SPARRY_LOCAL_VERSION}" "${SPARRY_LATEST_VERSION}" "${SPARRY_INSTALL_LOCATION}"
    printf "${FORMAT}\n" "7" "${TORBOT_NAME}" "${TORBOT_INSTALLED}" "${TORBOT_STATUS}" "${TORBOT_LOCAL_VERSION}" "${TORBOT_LATEST_VERSION}" "${TORBOT_INSTALL_LOCATION}"
    printf "%b" "${NC}"

    remove_temp_files
}

feature_install() {
    gather_latest_bot_information
    gather_local_bot_information

    # provide overview
    DIVIDER="=========================================================================================="
    HEADER="\n %-4s %-12s %-10s %-10s\n"
    FORMAT_OVERVIEW=" %-4s %-12s %-10s %-10s\n"
    FORMAT_INSTALLATION=" %-5s %-27s %-4s %-30s\n"
    WIDTH="90"
    printf "%b" "${BOLD}"
    printf "${HEADER}" "NR" "BOT" "INSTALLED" "DESCRIPTION"
    printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"
    printf "${FORMAT_OVERVIEW}" "1" "${BOTMANAGER_NAME}" "${BOTMANAGER_INSTALLED}" "${BOTMANAGER_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "2" "${SERVERBOT_NAME}" "${SERVERBOT_INSTALLED}" "${SERVERBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "3" "${BACKUPBOT_NAME}" "${BACKUPBOT_INSTALLED}" "${BACKUPBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "4" "${UPTIMEBOT_NAME}" "${UPTIMEBOT_INSTALLED}" "${UPTIMEBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "5" "${UPDATEBOT_NAME}" "${UPDATEBOT_INSTALLED}" "${UPDATEBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "6" "${SPARRY_NAME}" "${SPARRY_INSTALLED}" "${SPARRY_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}\n" "7" "${TORBOT_NAME}" "${TORBOT_INSTALLED}" "${TORBOT_DESCRIPTION}"

    # let the user choose
    while true
        do
            read -r -p ' Choose program to install (number): ' PROGRAM_NUMBER_TO_INSTALL
            [ "${PROGRAM_NUMBER_TO_INSTALL}" -ge '1' ] && [ "${PROGRAM_NUMBER_TO_INSTALL}" -le '7' ] && break
            notice 'enter number from 1 to 7 or press ctrl+c to abort'
        done

    # install chosen software    
    if [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '1' ]; then
        send_error_to_log "botmanager can't install itself"
        error 'botmanager: error: cannot install myself :('
    elif [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '2' ]; then
        if [ "${SERVERBOT_INSTALLED}" = 'YES' ]; then
            send_error_to_log "Can't install" "${SERVERBOT_NAME}" "because it is already installed"
            error 'botmanager: error: serverbot is already installed'
        fi
        printf "\n Installing %s\n" "${SERVERBOT_NAME}"
        printf "${FORMAT_INSTALLATION}" "(1/6)" "Downloading ${SERVERBOT_NAME}" "=>" "${SERVERBOT_PROGRAM_DESTINATION}"
        "${WGET}" -q "${SERVERBOT_PROGRAM_SOURCE}" -O "${SERVERBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(2/6)" "Setting ownership" "=>"  "${SERVERBOT_PROGRAM_OWNER}:${SERVERBOT_PROGRAM_GROUP}"
        chown "${SERVERBOT_PROGRAM_OWNER}:${SERVERBOT_PROGRAM_GROUP}" "${SERVERBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(3/6)" "Setting permissions" "=>" "${SERVERBOT_PROGRAM_ACCESS}"
        chmod "${SERVERBOT_PROGRAM_ACCESS}" "${SERVERBOT_PROGRAM_DESTINATION}"
        send_notice_to_log "Installed" "${SERVERBOT_PROGRAM_DESTINATION}" "succesfully"
        printf "${FORMAT_INSTALLATION}" "(4/6)" "Downloading configuration" "=>" "${SERVERBOT_CONFIG_DESTINATION}"
        "${WGET}" -q "${SERVERBOT_CONFIG_SOURCE}" -O "${SERVERBOT_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(5/6)" "Setting ownership" "=>" "${SERVERBOT_CONFIG_OWNER}:${SERVERBOT_CONFIG_GROUP}"
        chown "${SERVERBOT_CONFIG_OWNER}:${SERVERBOT_CONFIG_GROUP}" "${SERVERBOT_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(6/6)" "Setting permissions" "=>" "${SERVERBOT_CONFIG_ACCESS}"
        chmod "${SERVERBOT_CONFIG_ACCESS}" "${SERVERBOT_CONFIG_DESTINATION}"
        send_notice_to_log "Installed" "${SERVERBOT_CONFIG_DESTINATION}" "succesfully"
        printf "\n All done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '3' ]; then
        if [ "${BACKUPBOT_INSTALLED}" = 'YES' ]; then
            send_error_to_log "Can't install" "${BACKUPBOT_NAME}" "because it is already installed"
            error 'botmanager: error: backupbot is already installed'
        fi
        printf "\n Installing %s\n" "${BACKUPBOT_NAME}"
        printf "${FORMAT_INSTALLATION}" "(1/6)" "Downloading ${BACKUPBOT_NAME}" "=>" "${BACKUPBOT_PROGRAM_DESTINATION}"
        "${WGET}" -q "${BACKUPBOT_PROGRAM_SOURCE}" -O "${BACKUPBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(2/6)" "Setting ownership" "=>"  "${BACKUPBOT_PROGRAM_OWNER}:${BACKUPBOT_PROGRAM_GROUP}"
        chown "${BACKUPBOT_PROGRAM_OWNER}:${BACKUPBOT_PROGRAM_GROUP}" "${BACKUPBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(3/6)" "Setting permissions" "=>" "${BACKUPBOT_PROGRAM_ACCESS}"
        chmod "${BACKUPBOT_PROGRAM_ACCESS}" "${BACKUPBOT_PROGRAM_DESTINATION}"
        send_notice_to_log "Installed" "${BACKUPBOT_PROGRAM_DESTINATION}" "succesfully"
        printf "${FORMAT_INSTALLATION}" "(4/6)" "Downloading configuration" "=>" "${BACKUPBOT_CONFIG_DESTINATION}"
        "${WGET}" -q "${BACKUPBOT_CONFIG_SOURCE}" -O "${BACKUPBOT_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(5/6)" "Setting ownership" "=>" "${BACKUPBOT_CONFIG_OWNER}:${BACKUPBOT_CONFIG_GROUP}"
        chown "${BACKUPBOT_CONFIG_OWNER}:${BACKUPBOT_CONFIG_GROUP}" "${BACKUPBOT_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(6/6)" "Setting permissions" "=>" "${BACKUPBOT_CONFIG_ACCESS}"
        chmod "${BACKUPBOT_CONFIG_ACCESS}" "${BACKUPBOT_CONFIG_DESTINATION}"
        send_notice_to_log "Installed" "${BACKUPBOT_CONFIG_DESTINATION}" "succesfully"
        printf "\n All done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '4' ]; then
        if [ "${UPTIMEBOT_INSTALLED}" = 'YES' ]; then
            send_error_to_log "Can't install" "${UPTIMEBOT_NAME}" "because it is already installed"
            error 'botmanager: error: uptimebot is already installed'
        fi
        printf "\n Installing %s\n" "${UPTIMEBOT_NAME}"
        printf "${FORMAT_INSTALLATION}" "(1/9)" "Downloading ${UPTIMEBOT_NAME}" "=>" "${UPTIMEBOT_PROGRAM_DESTINATION}"
        "${WGET}" -q "${UPTIMEBOT_PROGRAM_SOURCE}" -O "${UPTIMEBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(2/9)" "Setting ownership" "=>"  "${UPTIMEBOT_PROGRAM_OWNER}:${UPTIMEBOT_PROGRAM_GROUP}"
        chown "${UPTIMEBOT_PROGRAM_OWNER}:${UPTIMEBOT_PROGRAM_GROUP}" "${UPTIMEBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(3/9)" "Setting permissions" "=>" "${UPTIMEBOT_PROGRAM_ACCESS}"
        chmod "${UPTIMEBOT_PROGRAM_ACCESS}" "${UPTIMEBOT_PROGRAM_DESTINATION}"
        send_notice_to_log "Installed" "${UPTIMEBOT_PROGRAM_DESTINATION}" "succesfully"
        printf "${FORMAT_INSTALLATION}" "(4/9)" "Downloading configuration" "=>" "${UPTIMEBOT_CONFIG_DESTINATION}"
        "${WGET}" -q "${UPTIMEBOT_CONFIG_SOURCE}" -O "${UPTIMEBOT_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(5/9)" "Setting ownership" "=>" "${UPTIMEBOT_CONFIG_OWNER}:${UPTIMEBOT_CONFIG_GROUP}"
        chown "${UPTIMEBOT_CONFIG_OWNER}:${UPTIMEBOT_CONFIG_GROUP}" "${UPTIMEBOT_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(6/9)" "Setting permissions" "=>" "${UPTIMEBOT_CONFIG_ACCESS}"
        chmod "${UPTIMEBOT_CONFIG_ACCESS}" "${UPTIMEBOT_CONFIG_DESTINATION}"
        send_notice_to_log "Installed" "${UPTIMEBOT_CONFIG_DESTINATION}" "succesfully"
        printf "${FORMAT_INSTALLATION}" "(7/9)" "Downloading targets.conf" "=>" "${UPTIMEBOT_USERCONF_DESTINATION}"
        "${WGET}" -q "${UPTIMEBOT_USERCONF_SOURCE}" -O "${UPTIMEBOT_USERCONF_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(8/9)" "Setting ownership" "=>" "${UPTIMEBOT_USERCONF_OWNER}:${UPTIMEBOT_USERCONF_GROUP}"
        chown "${UPTIMEBOT_USERCONF_OWNER}:${UPTIMEBOT_USERCONF_GROUP}" "${UPTIMEBOT_USERCONF_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(9/9)" "Setting permissions" "=>" "${UPTIMEBOT_USERCONF_ACCESS}"
        chmod "${UPTIMEBOT_USERCONF_ACCESS}" "${UPTIMEBOT_USERCONF_DESTINATION}"
        send_notice_to_log "Installed" "${UPTIMEBOT_USERCONF_DESTINATION}" "succesfully"
        printf "\n All done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '5' ]; then
        if [ "${UPDATEBOT_INSTALLED}" = 'YES' ]; then
            send_error_to_log "Can't install" "${UPDATEBOT_NAME}" "because it is already installed"
            error 'botmanager: error: updatebot is already installed'
        fi
        printf "\n Installing %s\n" "${UPDATEBOT_NAME}"
        printf "${FORMAT_INSTALLATION}" "(1/3)" "Downloading ${UPDATEBOT_NAME}" "=>" "${UPDATEBOT_PROGRAM_DESTINATION}"
        "${WGET}" -q "${UPDATEBOT_PROGRAM_SOURCE}" -O "${UPDATEBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(2/3)" "Setting ownership" "=>"  "${UPDATEBOT_PROGRAM_OWNER}:${UPDATEBOT_PROGRAM_GROUP}"
        chown "${UPDATEBOT_PROGRAM_OWNER}:${UPDATEBOT_PROGRAM_GROUP}" "${UPDATEBOT_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(3/3)" "Setting permissions" "=>" "${UPDATEBOT_PROGRAM_ACCESS}"
        chmod "${UPDATEBOT_PROGRAM_ACCESS}" "${UPDATEBOT_PROGRAM_DESTINATION}"
        send_notice_to_log "Installed" "${UPDATEBOT_PROGRAM_DESTINATION}" "succesfully"
        printf "\n All done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '6' ]; then
        if [ "${SPARRY_INSTALLED}" = 'YES' ]; then
            send_error_to_log "Can't install" "${SPARRY_NAME}" "because it is already installed"
            error 'botmanager: error: sparry is already installed'
        fi
        printf "\n Installing %s\n" "${SPARRY_NAME}"
        printf "${FORMAT_INSTALLATION}" "(1/6)" "Downloading ${SPARRY_NAME}" "=>" "${SPARRY_PROGRAM_DESTINATION}"
        "${WGET}" -q "${SPARRY_PROGRAM_SOURCE}" -O "${SPARRY_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(2/6)" "Setting ownership" "=>"  "${SPARRY_PROGRAM_OWNER}:${SPARRY_PROGRAM_GROUP}"
        chown "${SPARRY_PROGRAM_OWNER}:${SPARRY_PROGRAM_GROUP}" "${SPARRY_PROGRAM_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(3/6)" "Setting permissions" "=>" "${SPARRY_PROGRAM_ACCESS}"
        chmod "${SPARRY_PROGRAM_ACCESS}" "${SPARRY_PROGRAM_DESTINATION}"
        send_notice_to_log "Installed" "${SPARRY_PROGRAM_DESTINATION}" "succesfully"
        printf "${FORMAT_INSTALLATION}" "(4/6)" "Downloading configuration" "=>" "${SPARRY_CONFIG_DESTINATION}"
        "${WGET}" -q "${SPARRY_CONFIG_SOURCE}" -O "${SPARRY_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(5/6)" "Setting ownership" "=>" "${SPARRY_CONFIG_OWNER}:${SPARRY_CONFIG_GROUP}"
        chown "${SPARRY_CONFIG_OWNER}:${SPARRY_CONFIG_GROUP}" "${SPARRY_CONFIG_DESTINATION}"
        printf "${FORMAT_INSTALLATION}" "(6/6)" "Setting permissions" "=>" "${SPARRY_CONFIG_ACCESS}"
        chmod "${SPARRY_CONFIG_ACCESS}" "${SPARRY_CONFIG_DESTINATION}"
        send_notice_to_log "Installed" "${SPARRY_CONFIG_DESTINATION}" "succesfully"
        printf "\n All done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_INSTALL}" -eq '7' ]; then
        error 'botmanager: error: torbot is not finished yet'
    fi
    printf "%b" "${NC}"

    remove_temp_files
}

feature_remove() {
    gather_latest_bot_information
    gather_local_bot_information

    # provide overview
    DIVIDER="=========================================================================================="
    HEADER="\n %-4s %-12s %-10s %-10s\n"
    FORMAT_OVERVIEW=" %-4s %-12s %-10s %-10s\n"
    FORMAT_REMOVE=" %-5s %-43s %-4s %-30s\n"
    FORMAT_REMOVE_LONG=" %-5s %-52s %-4s %-30s\n"
    WIDTH="90"
    printf "%b" "${BOLD}"
    printf "${HEADER}" "NR" "BOT" "INSTALLED" "DESCRIPTION"
    printf "%${WIDTH}.${WIDTH}s\n" "${DIVIDER}"
    printf "${FORMAT_OVERVIEW}" "1" "${BOTMANAGER_NAME}" "${BOTMANAGER_INSTALLED}" "${BOTMANAGER_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "2" "${SERVERBOT_NAME}" "${SERVERBOT_INSTALLED}" "${SERVERBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "3" "${BACKUPBOT_NAME}" "${BACKUPBOT_INSTALLED}" "${BACKUPBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "4" "${UPTIMEBOT_NAME}" "${UPTIMEBOT_INSTALLED}" "${UPTIMEBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "5" "${UPDATEBOT_NAME}" "${UPDATEBOT_INSTALLED}" "${UPDATEBOT_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}" "6" "${SPARRY_NAME}" "${SPARRY_INSTALLED}" "${SPARRY_DESCRIPTION}"
    printf "${FORMAT_OVERVIEW}\n" "7" "${TORBOT_NAME}" "${TORBOT_INSTALLED}" "${TORBOT_DESCRIPTION}"

    # let the user choose
    while true
        do
            read -r -p ' Choose program to remove (number): ' PROGRAM_NUMBER_TO_REMOVE
            [ "${PROGRAM_NUMBER_TO_REMOVE}" -ge '1' ] && [ "${PROGRAM_NUMBER_TO_REMOVE}" -le '7' ] && break
            notice 'enter number from 1 to 7 or press ctrl+c to abort'
        done

    # remove chosen software
    if [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '1' ]; then
        send_error_to_log "botmanager can't remove itself"
        error 'botmanager: error: cannot remove myself :('
    elif [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '2' ]; then
        printf "\n Removing %s\n" "${SERVERBOT_NAME}"
        if [ -f "${SERVERBOT_PROGRAM_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(1/2)" "Found ${SERVERBOT_PROGRAM_DESTINATION}" "=>" "removing"
            rm "${SERVERBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Removed" "${SERVERBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(1/2)" "Can't find ${SERVERBOT_PROGRAM_DESTINATION}" "=>" "ignoring"
        fi
        if [ -f "${SERVERBOT_CONFIG_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(2/2)" "Found ${SERVERBOT_CONFIG_DESTINATION}" "=>" "removing"
            rm "${SERVERBOT_CONFIG_DESTINATION}"
            send_notice_to_log "Removed" "${SERVERBOT_CONFIG_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(2/2)" "Can't find ${SERVERBOT_CONFIG_DESTINATION}" "=>" "ignoring"
        fi
        printf "\nAll done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '3' ]; then
        printf "\n Removing %s\n" "${BACKUPBOT_NAME}"
        if [ -f "${BACKUPBOT_PROGRAM_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(1/2)" "Found ${BACKUPBOT_PROGRAM_DESTINATION}" "=>" "removing"
            rm "${BACKUPBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Removed" "${BACKUPBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(1/2)" "Can't find ${BACKUPBOT_PROGRAM_DESTINATION}" "=>" "ignoring"
        fi
        if [ -f "${BACKUPBOT_CONFIG_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(2/2)" "Found ${BACKUPBOT_CONFIG_DESTINATION}" "=>" "removing"
            rm "${BACKUPBOT_CONFIG_DESTINATION}"
            send_notice_to_log "Removed" "${BACKUPBOT_CONFIG_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(2/2)" "Can't find ${BACKUPBOT_CONFIG_DESTINATION}" "=>" "ignoring"
        fi
        printf "\nAll done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '4' ]; then
        printf "\n Removing %s\n" "${UPTIMEBOT_NAME}"
        if [ -f "${UPTIMEBOT_PROGRAM_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE_LONG}" "(1/3)" "Found ${UPTIMEBOT_PROGRAM_DESTINATION}" "=>" "removing"
            rm "${UPTIMEBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Removed" "${UPTIMEBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE_LONG}" "(1/3)" "Can't find ${UPTIMEBOT_PROGRAM_DESTINATION}" "=>" "ignoring"
        fi
        if [ -f "${UPTIMEBOT_CONFIG_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE_LONG}" "(2/3)" "Found ${UPTIMEBOT_CONFIG_DESTINATION}" "=>" "removing"
            rm "${UPTIMEBOT_CONFIG_DESTINATION}"
            send_notice_to_log "Removed" "${UPTIMEBOT_CONFIG_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE_LONG}" "(2/3)" "Can't find ${UPTIMEBOT_CONFIG_DESTINATION}" "=>" "ignoring"
        fi
        if [ -f "${UPTIMEBOT_USERCONF_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE_LONG}" "(3/3)" "Found ${UPTIMEBOT_USERCONF_DESTINATION}" "=>" "removing"
            rm "${UPTIMEBOT_USERCONF_DESTINATION}"
            send_notice_to_log "Removed" "${UPTIMEBOT_USERCONF_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE_LONG}" "(3/3)" "Can't find ${UPTIMEBOT_USERCONF_DESTINATION}" "=>" "ignoring"
        fi
        printf "\nAll done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '5' ]; then
        printf "\n Removing %s\n" "${UPDATEBOT_NAME}"
        if [ -f "${UPDATEBOT_PROGRAM_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(1/1)" "Found ${UPDATEBOT_PROGRAM_DESTINATION}" "=>" "removing"
            rm "${UPDATEBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Removed" "${UPDATEBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(1/1)" "Can't find ${UPDATEBOT_PROGRAM_DESTINATION}" "=>" "ignoring"
        fi
        printf "\nAll done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '6' ]; then
        printf "\n Removing %s\n" "${SPARRY_NAME}"
        if [ -f "${SPARRY_PROGRAM_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(1/2)" "Found ${SPARRY_PROGRAM_DESTINATION}" "=>" "removing"
            rm "${SPARRY_PROGRAM_DESTINATION}"
            send_notice_to_log "Removed" "${SPARRY_PROGRAM_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(1/2)" "Can't find ${SPARRY_PROGRAM_DESTINATION}" "=>" "ignoring"
        fi
        if [ -f "${SPARRY_CONFIG_DESTINATION}" ]; then
            printf "${FORMAT_REMOVE}" "(2/2)" "Found ${SPARRY_CONFIG_DESTINATION}" "=>" "removing"
            rm "${SPARRY_CONFIG_DESTINATION}"
            send_notice_to_log "Removed" "${SPARRY_CONFIG_DESTINATION}" "succesfully"
        else
            printf "${FORMAT_REMOVE}" "(2/2)" "Can't find ${SPARRY_CONFIG_DESTINATION}" "=>" "ignoring"
        fi
        printf "\nAll done! \\\( ^ ᴗ ^ )/\n\n"
    elif [ "${PROGRAM_NUMBER_TO_REMOVE}" -eq '7' ]; then
        error 'botmanager: error: torbot is not finished yet'
    fi
    printf "%b" "${NC}"

    remove_temp_files
}

feature_update() {
    feature_overview

    # update software
    FORMAT_UPDATE=" %-8s %-17s %-4s %-12s\n"
    printf "%b" "${BOLD}"
    printf " Updating software\n"
    if [ "${BOTMANAGER_INSTALLED}" = 'YES' ]; then
        if [ "${BOTMANAGER_STATUS}" = 'UPDATE' ]; then
            printf " Skipping update for %s because I can't update myself\n" "${BOTMANAGER_NAME}"
            send_notice_to_log "Updated" "${BOTMANAGER_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${BOTMANAGER_NAME}"
        fi
    fi
    if [ "${SERVERBOT_INSTALLED}" = 'YES' ]; then
        if [ "${SERVERBOT_STATUS}" = 'UPDATE' ]; then
            printf "${FORMAT_UPDATE}" "Updating" "${SERVERBOT_NAME} ${SERVERBOT_LOCAL_VERSION}" "=>" "${SERVERBOT_LATEST_VERSION}"         
            "${WGET}" -q "${SERVERBOT_PROGRAM_SOURCE}" -O "${SERVERBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${SERVERBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${SERVERBOT_NAME}"
        fi
    fi
    if [ "${BACKUPBOT_INSTALLED}" = 'YES' ]; then
        if [ "${BACKUPBOT_STATUS}" = 'UPDATE' ]; then
            printf "${FORMAT_UPDATE}" "Updating" "${BACKUPBOT_NAME} ${BACKUPBOT_LOCAL_VERSION}" "=>" "${BACKUPBOT_LATEST_VERSION}"
            "${WGET}" -q "${BACKUPBOT_PROGRAM_SOURCE}" -O "${BACKUPBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${BACKUPBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${BACKUPBOT_NAME}"
        fi
    fi
    if [ "${UPTIMEBOT_INSTALLED}" = 'YES' ]; then
        if [ "${UPTIMEBOT_STATUS}" = 'UPDATE' ]; then
            printf "${FORMAT_UPDATE}" "Updating" "${UPTIMEBOT_NAME} ${UPTIMEBOT_LOCAL_VERSION}" "=>" "${UPTIMEBOT_LATEST_VERSION}"
            "${WGET}" -q "${UPTIMEBOT_PROGRAM_SOURCE}" -O "${UPTIMEBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${UPTIMEBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${UPTIMEBOT_NAME}"
        fi
    fi
    if [ "${UPDATEBOT_INSTALLED}" = 'YES' ]; then
        if [ "${UPDATEBOT_STATUS}" = 'UPDATE' ]; then
            printf "${FORMAT_UPDATE}" "Updating" "${UPDATEBOT_NAME} ${UPDATEBOT_LOCAL_VERSION}" "=>" "${UPDATEBOT_LATEST_VERSION}"
            "${WGET}" -q "${UPDATEBOT_PROGRAM_SOURCE}" -O "${UPDATEBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${UPDATEBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${UPDATEBOT_NAME}"
        fi
    fi
    if [ "${SPARRY_INSTALLED}" = 'YES' ]; then
        if [ "${SPARRY_STATUS}" = 'UPDATE' ]; then
            printf "${FORMAT_UPDATE}" "Updating" "${SPARRY_NAME} ${SPARRY_LOCAL_VERSION}" "=>" "${SPARRY_LATEST_VERSION}"
            "${WGET}" -q "${SPARRY_PROGRAM_SOURCE}" -O "${SPARRY_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${SPARRY_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${SPARRY_NAME}"
        fi
    fi
    if [ "${TORBOT_INSTALLED}" = 'YES' ]; then
        if [ "${TORBOT_STATUS}" = 'UPDATE' ]; then
            printf "${FORMAT_UPDATE}" "Updating" "${TORBOT_NAME} ${TORBOT_LOCAL_VERSION}" "=>" "${TORBOT_LATEST_VERSION}"
            "${WGET}" -q "${TORBOT_PROGRAM_SOURCE}" -O "${TORBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${TORBOT_PROGRAM_DESTINATION}" "succesfully"
        else
            printf " No update available for %s\n" "${TORBOT_NAME}"
        fi
    fi
    printf "\nAll done! \\\( ^ ᴗ ^ )/\n\n"
    printf "%b" "${NC}"
}

feature_unattended_update() {
    gather_latest_bot_information
    gather_local_bot_information

    # update software
    if [ "${SERVERBOT_INSTALLED}" = 'YES' ]; then
        if [ "${SERVERBOT_STATUS}" = 'UPDATE' ]; then
            "${WGET}" -q "${SERVERBOT_PROGRAM_SOURCE}" -O "${SERVERBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${SERVERBOT_PROGRAM_DESTINATION}" "succesfully"
        fi
    fi
    if [ "${BACKUPBOT_INSTALLED}" = 'YES' ]; then
        if [ "${BACKUPBOT_STATUS}" = 'UPDATE' ]; then
            "${WGET}" -q "${BACKUPBOT_PROGRAM_SOURCE}" -O "${BACKUPBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${BACKUPBOT_PROGRAM_DESTINATION}" "succesfully"
        fi
    fi
    if [ "${UPTIMEBOT_INSTALLED}" = 'YES' ]; then
        if [ "${UPTIMEBOT_STATUS}" = 'UPDATE' ]; then
            "${WGET}" -q "${UPTIMEBOT_PROGRAM_SOURCE}" -O "${UPTIMEBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${UPTIMEBOT_PROGRAM_DESTINATION}" "succesfully"
        fi
    fi
    if [ "${UPDATEBOT_INSTALLED}" = 'YES' ]; then
        if [ "${UPDATEBOT_STATUS}" = 'UPDATE' ]; then
            "${WGET}" -q "${UPDATEBOT_PROGRAM_SOURCE}" -O "${UPDATEBOT_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${UPDATEBOT_PROGRAM_DESTINATION}" "succesfully"
        fi
    fi
    if [ "${SPARRY_INSTALLED}" = 'YES' ]; then
        if [ "${SPARRY_STATUS}" = 'UPDATE' ]; then
            "${WGET}" -q "${SPARRY_PROGRAM_SOURCE}" -O "${SPARRY_PROGRAM_DESTINATION}"
            send_notice_to_log "Updated" "${SPARRY_PROGRAM_DESTINATION}" "succesfully"
        fi
    fi

    remove_temp_files
}

####################################################################################################
# MAIN FUNCTIONS
####################################################################################################

botmanager_main() {
    requirement_os
    requirement_root

    if [ "${ARGUMENT_UPDATE}" = '1' ] && [ "${ARGUMENT_UNATTENDED}" = '1' ]; then
        feature_unattended_update
        exit 0
    elif [ "${ARGUMENT_OVERVIEW}" = '1' ]; then
        feature_overview
        exit 0
    elif [ "${ARGUMENT_INSTALL}" = '1' ]; then
        feature_install
        exit 0
    elif [ "${ARGUMENT_REMOVE}" = '1' ]; then
        feature_remove
        exit 0
    elif [ "${ARGUMENT_UPDATE}" = '1' ]; then
        feature_update
        exit 0
    elif [ "${ARGUMENT_CRON}" = '1' ]; then
        option_cron
        exit 0
    elif [ "${ARGUMENT_DISABLE_CRON}" = '1' ]; then
        option_disable_cron
        exit 0
    elif [ "${ARGUMENT_VERSION}" = '1' ]; then
        option_version
        exit 0
    elif [ "${ARGUMENT_HELP}" = '1' ]; then
        option_help
        exit 0
    elif [ "${ARGUMENT_NONE}" = '1' ]; then
        feature_overview
        exit 0
    # the overview is shown when no arguments were given
    else
        feature_overview
        exit 0
    fi
}

####################################################################################################
# CALL MAIN FUNCTIONS
####################################################################################################

botmanager_main
